### ISSUE TITLE
Cannot build the filesystem

### ISSUE THREAD

**Issue by kartoch** [maxonthegit/netkit-uml-filesystem#7]
I've the following errors when I trt to build the filesystem:

```
$ sudo make -f Makefile.devel  filesystem
======= Downloading base packages... =====
I: Retrieving Release
I: Retrieving Packages
I: Validating Packages
I: Resolving dependencies of required packages...
I: Resolving dependencies of base packages...
I: Found additional required dependencies: insserv libbz2-1.0 libdb5.1 libslang2 
I: Found additional base dependencies: libnfnetlink0 libsqlite3-0 
I: Checking component main on http://ftp.it.debian.org/debian...
E: Couldn't find these debs: libxapian15
make: *** [debian-base-packages-sid-i386.tgz] Error 1
```

**Comment by maxonthegit** [comment]
This is `debootstrap` failing. In the past we have resolved similar issues, due to `debootstrap` bugs and/or missing packages and/or broken dependencies in the repository, by manually getting the required packages instead. The filesystem Makefile includes an `ADDITIONAL_PACKAGES` variable that is used to fetch these packages. You may want to remove `libxapian15` from the list.

**Comment by kartoch** [comment]
It fixed the problem but I have another one:

```
I: Extracting libuuid1...
I: Extracting mount...
I: Extracting util-linux...
I: Extracting liblzma2...
I: Extracting xz-utils...
I: Extracting zlib1g...
I: Installing core packages...
W: Failure trying to run: chroot /home/kartoch/works/network/netkit-uml-filesystem-kartoch/mounted_fs dpkg --force-depends --install /var/cache/apt/archives/base-files_6.4_i386.deb /var/cache/apt/archives/base-passwd_3.5.22_i386.deb
make: *** [.base_system_installed] Error 1
```

If I try to investigate the problem:

```
$ sudo chroot /home/kartoch/works/network/netkit-uml-filesystem-kartoch/mounted_fs
I have no name!@kartoch:/# dpkg --force-depends --install /var/cache/apt/archives/base-files_6.4_i386.deb /var/cache/apt/archives/base-
passwd_3.5.22_i386.deb
dpkg: warning: parsing file '/var/lib/dpkg/status' near line 3 package 'dpkg':
 missing description
dpkg: warning: parsing file '/var/lib/dpkg/status' near line 3 package 'dpkg':
 missing maintainer
dpkg: warning: parsing file '/var/lib/dpkg/status' near line 3 package 'dpkg':
 missing architecture
dpkg-deb: error while loading shared libraries: libbz2.so.1.0: cannot open shared object file: No such file or directory
dpkg: error processing /var/cache/apt/archives/base-files_6.4_i386.deb (--install):
 subprocess dpkg-deb --control returned error exit status 127
dpkg-deb: error while loading shared libraries: libbz2.so.1.0: cannot open shared object file: No such file or directory
dpkg: error processing /var/cache/apt/archives/base-passwd_3.5.22_i386.deb (--install):
 subprocess dpkg-deb --control returned error exit status 127
Errors were encountered while processing:
 /var/cache/apt/archives/base-files_6.4_i386.deb
 /var/cache/apt/archives/base-passwd_3.5.22_i386.deb
```

If I remember well, It was a blocking problem because this is a problem in the installation process of debian and the sid distribution is deprecated (it was why I tried to build a lenny filesystem). Do you have a solution for this ?

Cheers,

Julien.

**Comment by maxonthegit** [comment]
Looks as if `debootstrap` has <i>forgotten</i> to install fundamental basic packages (libbz2, in this case) before initiating `dpkg` invocations.
This may be worked around either by forcing `debootstrap` to include the libbz2 package at an early stage (which you can achieve in the Makefile) or, in the extreme case when no other solution works, by unpacking the libbz2 package into the directory debootstrap is supposed to chroot into.

**Comment by a-kr** [comment]
I'm having the same problem with building _squeeze_ filesystem.

Including libbz2 (specifically, `libbz2-1.0`) in the ADDITIONAL_PACKAGES variable had no effect. Unpacking the package (retrieved from http://packages.debian.org/squeeze/i386/libbz2-1.0/download ) into `mounted-fs` directory worked: the build process successfully completed `I: Installing core packages...` stage and went on.

However, it has not finished successfully. The following log was produced (less important parts snipped for brevity):

```
...
I: Extracting zlib1g...
I: Installing core packages...
I: Unpacking required packages...
I: Unpacking libacl1...
...
I: Unpacking zlib1g...
I: Configuring required packages...
I: Configuring ncurses-base...
...
I: Configuring initscripts...
I: Configuring sysvinit...
I: Configuring e2fsprogs...
W: Failure while configuring required packages.
make: *** [.base_system_installed] Error 1
```

The error is rather cryptic to me and I do not know how to investigate the cause here.

**Comment by kartoch** [comment]
- relaunch the 'make' command with '-d' to have debug output of the makefile process
- Then, we you have identify the command line (probably 'debootstrap' as show by your outputs), launch it manually: you will have better output

**Comment by a-kr** [comment]
Perusing `mounted-fs/debootstrap/debootstrap.log` I was able to identify the problem: more missing dependencies. In the end, unpacking the following packages to `mounted-fs` directory _and_ adding them to ADDITIONAL_PACKAGES variable fixed the issue for me:
- libbz2-1.0
- insserv
- libdb4.8
- libsqlite3-0
- libnfnetlink0

**Comment by kartoch** [comment]
Based on unmaintained debians, rotten issue, closing it
